language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: gE5z93VnzmnGDCrEgeDvRBashY5pDXSOq03SY2QPvXn2n5mfysbVbOkjTbwvCl52HNSY0Xqnx91cUYscmZdM9NJVGavJ0B2hr3KomNqyl4b6TaTIt4rBA9Nx3s9vDAl05VEZn2foe5Hvs2WVkJ4b9RmUxUim51wVSixvdFq0e6m8PYwHjIqDeZacBYd9OIHctC6X4D2ZtAodx/KOwamZgfOYePsi7n+F537uilpTDEiL5uXxtzCVHRtwBlTi2O2KojyHCXSmEjBxOTy+NvOrOTB36JDp3Ttup/rtBF5f1zyDIWHLdebyOqhCz+96wqcI9BLt94TOrpSPgVC/Yth00FZYjG+RC00Dh4T/rMnWknAmSghO7dVGV284h7fy0LbwSPg3MQzFCK4iCmF+TpA+WMNPx2AAC6x7Ar5hKafoHJ940YzshXj6Eak6z9jrgJIcO2AXHTqpgzHZqu2aSLhooBf41AbeZF2ry3bjUrVeZ+CovehQUCdcxcnA8koh/RVaHz0F8sdBKYTSYoltGci8PI5+kkzAnvwZ/jnf9JUxIk1QdfspXPwI6zUzRCfbJQ74GsJ8WwaNNK5vOkOF1Opx+ll4DvXGBpESiTG0MYNyzhzaRALfXKeSM9DMGA7Y75Lf0fd6fTcP7khha2gUBixSbnwaw7iVb6fHW16KTJ8yijk=
  app: sweater-weather-lriff
  on:
    repo: sweater-weather-api
    branch: main
notifications:
  email:
    on_success: never
    on_failure: never
cache:
- bundler
